import type { TopicGuide } from "@/types/topic-guide";

export const printerGuides: TopicGuide[] = [
  {
    slug: "tipos-impresoras-3d", title: "Tipos de impresoras 3D: qué cambia entre filamento, resina y polvo", shortTitle: "Elige tu impresora 3D", category: "Impresoras y tecnologías",
    description: "Compara FDM, resina y polvo, distingue CoreXY de una tecnología de impresión y elige por pieza, material, espacio y trabajo posterior.",
    lead: "Antes de comparar máquinas, decide qué quieres fabricar. Un organizador, una miniatura y una pieza de nylon pueden pedir procesos muy distintos.",
    takeaway: "Elige primero el proceso y el material; después compara las máquinas capaces de resolver esa pieza.", heroMedia: "corexy", heroCaption: "Una Bambu Lab X1 Carbon con AMS: ejemplo de FDM CoreXY cerrada. La fotografía identifica la arquitectura; no constituye una recomendación de compra.",
    sections: [
      { id: "mapa", title: "Tres familias para situarte", table: { headings: ["Proceso", "Materia prima", "Qué conviene valorar"], rows: [["FDM / FFF", "Filamento termoplástico", "Geometría, capas, soportes, material y repetibilidad"], ["SLA / MSLA / DLP", "Resina fotopolimérica", "Detalle, orientación, lavado, curado y manipulación"], ["SLS / MJF", "Polvo polimérico", "Lote, retirada de polvo, acabado y servicio de fabricación"]] }, paragraphs: ["CoreXY, cartesiana y delta describen maneras de mover los ejes. No son alternativas equivalentes a filamento, resina o polvo. Una CoreXY puede imprimir con el mismo filamento que una impresora de cama móvil."] },
      { id: "filamento", title: "FDM: una bobina y muchas posibilidades", media: "fdm-cartesian", caption: "Prusa i3 abierta: un ejemplo de arquitectura con cama móvil.", paragraphs: ["El extrusor deposita material fundido siguiendo trayectorias. Los organizadores, prototipos y piezas a medida son buenos ejercicios para aprender cómo influyen orientación, paredes y soportes.", "Una cama que se desplaza necesita espacio libre alrededor. En una CoreXY el movimiento del cabezal se organiza de otra forma; el cerramiento es otra característica que debes comprobar por separado. Ni la forma de la máquina ni una velocidad anunciada garantizan por sí solas la calidad."], bullets: ["Comprueba las dimensiones de tu pieza, no solo el volumen total anunciado.", "Busca perfiles de laminado, repuestos y documentación de mantenimiento.", "Para materiales exigentes, verifica boquilla, cama, cámara y requisitos del fabricante."], links: [{ label: "Preparar una impresión FDM", href: "/guia-impresion-3d-fdm" }] },
      { id: "resina", title: "Resina: el detalle incluye trabajo después de imprimir", media: "resin", caption: "Formlabs Form 2: equipo SLA con láser. No es una impresora MSLA de pantalla LCD.", paragraphs: ["SLA con láser, MSLA con pantalla LCD y DLP con proyector exponen resina mediante luz. Se emplean para superficies y detalles finos, pero las resinas tienen propiedades diferentes: no deduzcas resistencia, flexibilidad o biocompatibilidad del nombre del proceso.", "Incluye en la decisión el espacio de lavado, el poscurado cuando corresponda, la protección indicada por la ficha de seguridad y la gestión de residuos. La pieza recién salida de la máquina no siempre está lista para utilizar."], links: [{ label: "Comparar filamento y resina", href: "/filamento-vs-resina" }] },
      { id: "polvo", title: "Polvo: otra forma de producir lotes", media: "sls", caption: "Sistema SLS Sinterit Lisa Pro junto a equipos de gestión de polvo y posprocesado.", paragraphs: ["En SLS de polímeros, un láser consolida zonas de un lecho de polvo. En MJF se emplean agentes y energía térmica. El polvo que rodea la pieza ayuda a sostenerla, pero hay que poder retirarlo de cavidades y conductos.", "Para pocas piezas, pedir presupuesto a un servicio permite comparar el resultado sin comprar toda la instalación. Envía el archivo y un plano con las cotas que importan: el proveedor debe conocer material, acabado y función."], links: [{ label: "SLS frente a MJF", href: "/impresion-3d-polvo-sls-mjf" }] },
      { id: "compra", title: "Qué mirar antes de comprar", table: { headings: ["Tu objetivo", "La comprobación que importa"], rows: [["Aprender y hacer organizadores", "Primeras capas fiables, perfiles y mantenimiento comprensible"], ["Miniaturas y presentación", "Detalle visible después del acabado, tamaño y manipulación"], ["Piezas funcionales", "Material compatible, orientación y pruebas representativas"], ["Series pequeñas", "Piezas válidas por jornada y minutos de trabajo manual"], ["Varios colores", "Cambios, purga, residuos y duración del trabajo completo"]] }, paragraphs: ["Lleva a la comparación una pieza sencilla que represente tu uso. Pide ver el perfil, el tiempo completo y el acabado que se obtiene con él. Compara también el acceso para cambiar consumibles y el coste de una interrupción.", "Si todavía no sabes qué fabricar, empezar por definir una pieza evita pagar por prestaciones que no vas a utilizar. Una impresora grande no resuelve automáticamente tolerancias, diseño o falta de demanda."], links: [{ label: "Ideas de productos para validar", href: "/que-vender-impresion-3d" }, { label: "Calcular el coste de una pieza", href: "/calculadora-precio-impresion-3d" }] }
    ],
    sources: [{ label: "Prusa · Tipos de impresoras y diferencias", href: "https://help.prusa3d.com/article/types-of-printers-and-their-differences_112464" }, { label: "Formlabs · Comparación FDM, SLA y SLS", href: "https://formlabs.com/global/blog/fdm-vs-sla-vs-sls-how-to-choose-the-right-3d-printing-technology/" }, { label: "Prusa · Cómo elegir una impresora", href: "https://www.prusa3d.com/p/how-to-choose-a-3d-printer/" }]
  },
  {
    slug: "filamento-vs-resina", title: "Filamento o resina: qué impresora 3D elegir para tu proyecto", shortTitle: "Filamento frente a resina", category: "Comparativas de impresión",
    description: "FDM frente a SLA y MSLA: compara detalle, material, soportes, trabajo posterior y coste completo según la pieza que necesitas fabricar.",
    lead: "No hace falta declarar una tecnología ganadora. Hace falta saber qué pieza quieres obtener y qué trabajo estás dispuesto a hacer para terminarla.", takeaway: "Compara piezas acabadas y tiempo completo, no solo resolución o precio de la máquina.", heroMedia: "resin", heroCaption: "Una Form 2 de resina SLA. Los equipos MSLA usan otra forma de exposición, aunque también trabajan con resina.",
    sections: [
      { id: "comparacion", title: "Las diferencias que cambian tu trabajo", table: { headings: ["Criterio", "Filamento FDM", "Resina"], rows: [["Construcción", "Boquilla y recorridos de extrusión", "Exposición de resina mediante luz"], ["Detalle", "Depende de boquilla, capas y geometría", "Apta para detalle fino; depende de óptica, material y orientación"], ["Después de imprimir", "Retirar soportes y acabar cuando haga falta", "Lavar y realizar el tratamiento que indique la resina"], ["Material", "Termoplásticos con perfiles específicos", "Fotopolímeros con propiedades y curados específicos"], ["Espacio", "Máquina, bobinas y entorno de trabajo", "Máquina más manipulación, lavado, curado y residuos"]] } },
      { id: "pieza", title: "Tres piezas, tres decisiones", paragraphs: ["Para un separador de cajón, empieza comprobando dimensiones, rigidez de las paredes y superficie de apoyo. FDM permite explorar esos requisitos con un diseño simple y un termoplástico adecuado.", "Para una miniatura, estudia los rasgos pequeños que deben sobrevivir a la retirada de soportes y al acabado. Una resina apropiada puede encajar, pero el detalle de la pantalla no equivale por sí solo al detalle del objeto terminado.", "Para un clip o una carcasa, compara material, flexión, temperatura y repetición. Ni todas las resinas son frágiles ni cualquier filamento sirve para una pieza funcional: exige datos del material concreto y prueba la zona crítica."], media: "fdm-cartesian", caption: "Equipo FDM de filamento. El material y el perfil determinan parte del resultado, además de la máquina." },
      { id: "coste", title: "Qué falta en una comparación de precio por gramo", bullets: ["Soportes, purgas y muestras descartadas también consumen material.", "La limpieza, retirada de soportes y acabado ocupan tiempo de trabajo.", "Incluye consumibles del proceso y su mantenimiento.", "Compara la misma cantidad de piezas útiles, con un acabado equivalente."], paragraphs: ["Haz una ficha con material consumido, horas de máquina, minutos manuales y unidades válidas. Si necesitas diez piezas y obtienes ocho, no dividas el coste entre diez. Para resina, adapta los consumibles y fases: una cuenta pensada para filamento no incluye automáticamente lavado y poscurado."], links: [{ label: "Calculadora de precio para FDM", href: "/calculadora-precio-impresion-3d" }] },
      { id: "espacio", title: "Una mesa adecuada forma parte del proceso", paragraphs: ["Lee las instrucciones y la ficha de seguridad del consumible antes de organizar el puesto. En resina, evita contacto con material sin curar y gestiona resina y líquidos de limpieza según las indicaciones aplicables; no se vierten al desagüe.", "En FDM también importan el entorno y las emisiones del material. Una tapa no sustituye evaluar el espacio de trabajo ni la ventilación necesaria. Selecciona el proceso que puedas operar y mantener correctamente."], links: [{ label: "Elegir por tipo de impresora", href: "/tipos-impresoras-3d" }] },
      { id: "prueba", title: "Una comparación pequeña antes de decidir", steps: ["Dibuja una muestra con un detalle, una pared y una cota representativos.", "Define el acabado y el ajuste que considerarás aceptables.", "Solicita o fabrica ambas versiones con material y perfil registrados.", "Mide después del tratamiento completo y compara tiempo, coste y descarte.", "Elige por el requisito que de verdad limita tu proyecto."], paragraphs: ["Esta prueba propuesta no es un ensayo realizado por CADLAB3D. Sirve para que obtengas evidencia comparable en tu propio caso."] }
    ], sources: [{ label: "Formlabs · FDM, SLA y SLS", href: "https://formlabs.com/global/blog/fdm-vs-sla-vs-sls-how-to-choose-the-right-3d-printing-technology/" }, { label: "Prusa · Diferencias entre procesos", href: "https://help.prusa3d.com/article/types-of-printers-and-their-differences_112464" }]
  },
  {
    slug: "impresion-3d-polvo-sls-mjf", title: "Impresión 3D en polvo: diferencias entre SLS y MJF", shortTitle: "Polvo: SLS y MJF", category: "Fabricación avanzada",
    description: "Cómo funcionan SLS y MJF con polvo polimérico, qué cambia en soportes y acabado y qué información enviar al pedir piezas a un servicio.",
    lead: "Imprimir con polvo no significa necesariamente imprimir metal. SLS y MJF se utilizan para piezas de polímero y requieren una preparación diferente a FDM.", takeaway: "Diseña también la salida del polvo y define el acabado y las cotas críticas antes de pedir precio.", heroMedia: "sls", heroCaption: "Sistema SLS profesional Sinterit Lisa Pro con gestión de polvo. Esta foto no representa una máquina MJF.",
    sections: [
      { id: "proceso", title: "Qué hace cada proceso", table: { headings: ["Aspecto", "SLS", "MJF"], rows: [["Cómo se consolida", "Un láser recorre el lecho de polvo", "Agentes de fusión y detalle, con aplicación de energía térmica"], ["Familia tratada aquí", "Polímeros", "Polímeros"], ["Apoyo de la pieza", "Polvo circundante", "Polvo circundante"], ["Después del ciclo", "Enfriamiento, retirada de polvo y acabado", "Enfriamiento, retirada de polvo y acabado"]] }, paragraphs: ["La comparación es del principio de fabricación. El material disponible, el color, el acabado y las prestaciones dependen del sistema y del servicio contratado. No asignes a cualquier pieza unas propiedades vistas en otra ficha comercial."] },
      { id: "soportes", title: "Sin soportes de FDM no significa sin restricciones", paragraphs: ["El lecho ayuda a sostener la geometría, pero una cavidad cerrada puede retener polvo. Piensa cómo se limpiará una pieza hueca y consulta el tamaño y la posición de las aperturas con el proveedor.", "Las holguras de un conjunto móvil, los muros delgados y las superficies extensas siguen teniendo límites. No traslades automáticamente los valores que usas con una boquilla FDM; pide las reglas de diseño del proceso y material elegidos."], bullets: ["Señala cavidades, conductos y zonas difíciles de limpiar.", "Indica qué superficies encajan o apoyan en otra pieza.", "Aclara si necesitas roscas, insertos o mecanizado posterior."] },
      { id: "series", title: "Una caja, una bisagra y un lote", paragraphs: ["Una caja puede interesarte por la libertad de forma y la integración de fijaciones. Para una bisagra, la pregunta es si material, espesor y orientación soportan el movimiento previsto. Para un lote, importan repetición dimensional, acabado y unidades aceptadas.", "Pide una muestra de la región funcional antes de encargar todas las unidades. Conserva el informe de inspección y el archivo que realmente se fabricó; una modificación de CAD puede cambiar el ajuste aunque el nombre del fichero sea parecido."] },
      { id: "presupuesto", title: "Qué enviar para recibir presupuestos comparables", steps: ["Modelo en el formato solicitado y unidades confirmadas.", "Plano con dimensiones y tolerancias importantes.", "Cantidad, uso, material y acabado necesarios.", "Criterio de aceptación y documentación que debe entregar el proveedor.", "Plazo completo, transporte y operaciones posteriores incluidas."], paragraphs: ["Compara ofertas con el mismo alcance. Un precio por pieza puede incluir solo fabricación y otro incorporar teñido, limpieza adicional o control dimensional. Esas diferencias deben resolverse antes de elegir."], links: [{ label: "Preparar archivos de intercambio", href: "/blog/errores-exportar-archivos-cad" }, { label: "Entender la impresión metálica", href: "/impresion-3d-metal" }] }
    ], sources: [{ label: "Prusa · SLS y familias de impresión", href: "https://help.prusa3d.com/article/types-of-printers-and-their-differences_112464" }, { label: "HP · Principio de Multi Jet Fusion", href: "https://h20195.www2.hp.com/v2/GetPDF.aspx/4aa6-8157eew.pdf" }, { label: "Formlabs · Selección de tecnología", href: "https://formlabs.com/global/blog/fdm-vs-sla-vs-sls-how-to-choose-the-right-3d-printing-technology/" }]
  },
  {
    slug: "impresion-3d-metal", title: "Impresión 3D en metal: LPBF, DMLS y cuándo pedir una pieza", shortTitle: "Cómo se imprime en metal", category: "Fabricación avanzada",
    description: "Distingue LPBF, DMLS y SLM de otros procesos metálicos. Revisa diseño, soportes, acabado, tolerancias y qué pedir a un proveedor.",
    lead: "Sí, se pueden fabricar piezas metálicas por impresión 3D. La pregunta útil es qué proceso, aleación y operaciones posteriores necesita la pieza.", takeaway: "El archivo impreso no cierra el trabajo: define tratamientos, superficies funcionales e inspección con el fabricante.", heroMedia: "metal", heroCaption: "Fotografía real de impresión SLM en una TRUMPF TruPrint 1000, facilitada por FZU. No es un equipo de CADLAB3D.",
    sections: [
      { id: "siglas", title: "LPBF, DMLS y SLM: cómo leer las siglas", paragraphs: ["LPBF describe la fusión de un lecho de polvo mediante láser. DMLS y SLM son denominaciones empleadas en este ámbito; EOS sitúa su tecnología DMLS dentro de Laser Powder Bed Fusion.", "No todas las impresoras metálicas trabajan así. Hay procesos de deposición dirigida, unión mediante aglutinante y extrusión de material ligado que necesitan otros equipos y fases. Identifica la ruta completa del proveedor antes de comparar geometría o propiedades."], table: { headings: ["Pregunta", "Qué confirmar"], rows: [["¿Qué metal?", "Aleación y estado final especificados"], ["¿Qué proceso?", "Tecnología y equipo adecuados para esa aleación"], ["¿Cómo se termina?", "Retirada de soportes, tratamientos y acabado previstos"], ["¿Cómo se acepta?", "Cotas, superficie y comprobaciones acordadas"]] } },
      { id: "uso", title: "Qué geometrías justifican estudiar el proceso", paragraphs: ["Un conducto interior difícil de mecanizar, una pieza que integra varios componentes o un diseño condicionado por el peso pueden justificar consultar fabricación aditiva. El beneficio debe compararse con alternativas y con el coste completo.", "Para una placa plana con taladros sencillos, estudia también corte y mecanizado. La impresión no gana automáticamente por tratarse de una pieza compleja en pantalla: importan cantidad, material, accesibilidad y requisitos de acabado."] },
      { id: "diseno", title: "El diseño incluye orientación y operaciones posteriores", bullets: ["Acuerda orientación y soportes con quien vaya a fabricar.", "Reserva material en las superficies que deban mecanizarse.", "Permite retirar polvo de canales y cavidades.", "Separa tolerancias generales de las cotas realmente funcionales.", "Comprueba que las superficies puedan inspeccionarse y acabarse."], paragraphs: ["Una cara impresa no equivale a una cara mecanizada. Si tienes un asiento, una unión o una rosca con requisitos definidos, indícalos en el plano y pide que el presupuesto incluya su terminación."] },
      { id: "proveedor", title: "Del modelo a un pedido revisable", steps: ["Describe la función, el entorno y la aleación requerida.", "Entrega modelo y plano, con revisión y unidades identificadas.", "Solicita revisión de fabricabilidad y operaciones posteriores.", "Acordad material, tratamientos, inspección y criterios de aceptación.", "Empieza con la muestra o cantidad que permita comprobar el riesgo del proyecto."], paragraphs: ["La fabricación con polvo metálico requiere instalaciones y procedimientos específicos. Esta guía ayuda a preparar una consulta a un servicio; no describe cómo operar una máquina ni acredita una pieza para un uso crítico.", "No publiques una carga admisible o una certificación basándote solo en una fotografía. Si el uso exige trazabilidad o ensayos, deben formar parte de la contratación y de la documentación final."], links: [{ label: "Preparar la documentación técnica", href: "/guia-documentacion-tecnica" }, { label: "Diferenciar metal de polvo polimérico", href: "/impresion-3d-polvo-sls-mjf" }] }
    ], sources: [{ label: "EOS · DMLS y Laser Powder Bed Fusion", href: "https://www.eos.info/about-us/what-we-do/dmls" }, { label: "FZU · Fotografía documentada del proceso SLM", href: "https://commons.wikimedia.org/wiki/File:FZU_3Dprinting_2.jpg" }]
  }
];
