import type { TopicGuide } from "@/types/topic-guide";

export const softwareGuides: TopicGuide[] = [
  {
    slug: "programas-modelado-3d", title: "Programas de modelado 3D: Blender, FreeCAD, Fusion, SOLIDWORKS y Creo", shortTitle: "Qué programa de modelado elegir", category: "CAD y modelado",
    description: "Compara cinco programas por tarea: modelado orgánico, piezas paramétricas, ensamblajes, planos e impresión 3D. Revisa también la licencia de uso.",
    lead: "El mejor punto de partida depende de lo que necesitas cambiar: una forma, una cota, un ensamblaje o una imagen. Elegir por esa tarea evita aprender un programa que no encaja con el proyecto.", takeaway: "Para una pieza definida por medidas, empieza por CAD paramétrico; para escultura y una escena visual, estudia un flujo de mallas. Puedes combinar ambos.", heroMedia: "freecad", heroCaption: "FreeCAD 1.0: pieza y árbol de operaciones en PartDesign. La captura documenta esa versión, no todas las interfaces actuales.",
    sections: [
      { id: "comparativa", title: "Cinco programas, necesidades diferentes", table: { headings: ["Programa", "Dónde encaja", "Qué conviene comprobar"], rows: [["Blender", "Mallas, escultura, animación y presentación", "Escala, topología y preparación de la malla para fabricar"], ["FreeCAD", "Piezas paramétricas, croquis y documentación", "Flujo de trabajo y formatos necesarios para tu entrega"], ["Autodesk Fusion", "Diseño con herramientas integradas de fabricación", "Funciones del plan y permiso para uso comercial"], ["SOLIDWORKS", "Piezas, ensamblajes y planos en un flujo mecánico", "Producto y modalidad de licencia; no confundir con xDesign"], ["Creo", "Diseño paramétrico de producto e ingeniería", "Paquete, módulos y acceso a una licencia adecuada"]] }, paragraphs: ["Esta tabla compara enfoques de trabajo documentados. No es una clasificación de rendimiento ni una prueba cronometrada entre equipos."] },
      { id: "malla-solido", title: "Una carcasa y una figura no piden el mismo flujo", paragraphs: ["Para una carcasa, puede importar cambiar el ancho conservando taladros, espesores y apoyos. Un historial con croquis restringidos permite expresar esas relaciones y revisar qué operación depende de cada medida.", "Para una figura orgánica, suele ser más directo trabajar con una malla o escultura. Blender permite además preparar materiales, iluminación y animación. Poder darle forma al objeto no significa que ya esté listo para impresión: revisa espesor, escala y geometría cerrada."], media: "blender-modeling", caption: "Blender 4.3.2 mostrando una malla de Suzanne. Captura de referencia con su versión identificada.", links: [{ label: "Entender el CAD paramétrico", href: "/guia-cad-parametrico" }, { label: "Comprobar un STL antes de imprimir", href: "/blog/preparar-archivo-stl-impresion-3d" }] },
      { id: "licencias", title: "Gratis, educativo y comercial son cosas diferentes", paragraphs: ["Blender y FreeCAD permiten uso comercial del programa. Eso no cambia la licencia de un modelo, textura o complemento de otra persona. Conserva la procedencia de los recursos que incorporas.", "Fusion Personal está destinado a proyectos personales no comerciales. No interpretes un umbral económico aislado como un permiso general para vender piezas; revisa las condiciones del plan que utilizas.", "SOLIDWORKS y Creo tienen distintas modalidades. Comprueba las restricciones de una licencia educativa o personal antes de usarla para pedidos. También importan los formatos de salida y si otros usuarios podrán abrir tus archivos."], links: [{ label: "Preparar productos y revisar licencias", href: "/que-vender-impresion-3d#licencias" }] },
      { id: "ejercicio", title: "Prueba una misma pieza antes de decidir", steps: ["Dibuja una pequeña caja con dos agujeros y una tapa.", "Cambia el ancho y observa qué relaciones se conservan.", "Comprueba si puedes preparar el ensamblaje y las cotas que necesitas.", "Exporta el formato previsto y ábrelo en el siguiente programa del flujo.", "Anota qué pasos entiendes, dónde pierdes tiempo y qué documentación encuentras."], paragraphs: ["La comparación será más útil si repites el mismo encargo. Un render atractivo puede ocultar una geometría difícil de modificar; un modelo bien acotado puede necesitar otra herramienta para presentarlo."], links: [{ label: "SOLIDWORKS frente a Creo para aprender", href: "/blog/solidworks-vs-creo-estudiantes" }, { label: "Pasar del modelo al render", href: "/keyshot-vs-blender-renderizado" }] },
      { id: "entrega", title: "Elige también cómo vas a entregar el trabajo", paragraphs: ["Guarda el archivo editable cuando necesites futuras revisiones. Usa un formato neutro de sólidos cuando el destinatario lo requiera y una malla cuando sea adecuada para el laminador. Una exportación no conserva necesariamente el historial del programa original.", "Antes de enviar, reabre el archivo, confirma unidades y revisa que no falten cuerpos. Ese hábito ahorra más problemas que cambiar de software cada vez que aparece una dificultad."], links: [{ label: "Errores al exportar archivos CAD", href: "/blog/errores-exportar-archivos-cad" }] }
    ],
    sources: [{ label: "Blender · Funciones y licencia", href: "https://www.blender.org/about/license/" }, { label: "Blender · Suite de creación 3D", href: "https://www.blender.org/features/" }, { label: "FreeCAD · Funciones", href: "https://www.freecad.org/features.php" }, { label: "Autodesk · Condiciones de Fusion Personal", href: "https://www.autodesk.com/products/fusion-360/personal" }, { label: "SOLIDWORKS · Modalidades", href: "https://www.solidworks.com/how-to-buy" }, { label: "PTC · Creo", href: "https://www.ptc.com/en/products/creo" }]
  },
  {
    slug: "keyshot-vs-blender-renderizado", title: "KeyShot o Blender: comparar renderizado 3D de producto", shortTitle: "KeyShot frente a Blender", category: "Renderizado y presentación",
    description: "Compara el flujo de KeyShot Studio y Blender para renderizar productos: geometría CAD, materiales, luces, cámaras, animación y licencia.",
    lead: "Un buen render hace comprensible la forma, el material y la escala. La elección del programa depende del origen del modelo y de cuánto quieras construir alrededor de él.", takeaway: "Compara el flujo completo de tu proyecto. Un programa pensado para presentar CAD y una suite de creación 3D pueden resolver la misma imagen por caminos distintos.", heroMedia: "keyshot-render", heroCaption: "Render de producto realizado con KeyShot por 以秀 陳. Referencia externa histórica, no un render ni un ensayo de CADLAB3D.",
    sections: [
      { id: "comparar", title: "Qué cambia en el trabajo diario", table: { headings: ["Aspecto", "KeyShot Studio", "Blender"], rows: [["Punto de partida", "Visualización de producto a partir de geometría importada", "Creación y edición de una escena 3D completa"], ["Materiales y luces", "Flujo centrado en presentar el producto", "Nodos, iluminación y herramientas integradas de escena"], ["Render", "Opciones de CPU y GPU según configuración compatible", "Cycles y EEVEE con enfoques distintos"], ["Modelado y animación", "Preparación de modelos importados y animación de producto, cámaras y materiales", "Modelado, escultura, rigging, animación y composición"], ["Licencia", "Comercial; modalidades con condiciones específicas", "Software libre, compatible con trabajo comercial"]] }, paragraphs: ["La disponibilidad de funciones depende de versión, plan y equipo. No se ha realizado una prueba de velocidad entre ambos; una cifra de un ordenador ajeno no predice el tiempo de tu escena."] },
      { id: "flujo", title: "Del CAD al render, en seis pasos", steps: ["Limpia geometría y nombres; conserva una copia del modelo de fabricación.", "Comprueba unidades, normales y resolución de superficies curvas.", "Asigna materiales con una escala de textura coherente.", "Empieza con una iluminación sencilla y ajusta los reflejos que describen la forma.", "Elige cámara y encuadre según el detalle que quieres explicar.", "Revisa la imagen a tamaño de entrega antes de aumentar resolución o muestras."], paragraphs: ["Un radio pequeño puede ser importante para leer el borde con luz. Una textura mal escalada puede hacer que una pieza de plástico parezca una maqueta. Corrige esas decisiones antes de gastar más tiempo de cálculo."], links: [{ label: "Preparar correctamente la geometría", href: "/blog/errores-exportar-archivos-cad" }] },
      { id: "blender", title: "Cycles y EEVEE: empieza por la imagen que necesitas", media: "blender-render", caption: "Classroom, de Christophe Seux: ejemplo de escena renderizada en Blender, publicado bajo CC0.", paragraphs: ["Cycles es el motor de trazado de rayos de Blender. EEVEE utiliza un enfoque orientado al render en tiempo real. La elección afecta al flujo y a cómo se resuelven ciertos efectos; no son dos botones que deban dar siempre una imagen idéntica.", "Para una prueba de composición, trabaja con una resolución moderada y una escena controlada. Para la entrega, comprueba ruido, transparencias, sombras y reflejos. Reducir geometría innecesaria y texturas desproporcionadas puede ayudar, pero conserva lo que sí aparece en cámara."] },
      { id: "keyshot", title: "Cuándo estudiar KeyShot", paragraphs: ["Si recibes modelos CAD y tu tarea principal es preparar imágenes de producto, revisa la compatibilidad de importación y el mecanismo de actualización desde tu programa. Una conexión compatible puede ahorrar trabajo cuando cambia la geometría.", "Prueba el material, las variantes y las cámaras que realmente necesitas. Revisa las condiciones de la licencia: la modalidad educativa se destina al aprendizaje y tiene restricciones propias sobre los archivos. No la presupongas válida para encargos comerciales."], links: [{ label: "Elegir programa de modelado", href: "/programas-modelado-3d" }] },
      { id: "comparacion-propia", title: "Cómo hacer una comparación que te sirva", paragraphs: ["Usa una misma pieza, un acabado mate y otro brillante, la misma resolución y un ordenador identificado. Anota tiempo para preparar la escena, corregir un cambio y producir la imagen final.", "Valora también si el archivo lo puede mantener otra persona. El programa que exige menos ajustes en un encargo puede pedir más preparación en otro. La decisión se apoya en tu flujo, no en un ganador universal."], bullets: ["Comprueba que las imágenes representan la pieza y sus materiales con claridad.", "Identifica un render como render si se usa para mostrar un producto aún no fabricado.", "Para vender un objeto físico, prepara también fotografías de la muestra real."], links: [{ label: "Fotografías y validación antes de vender", href: "/que-vender-impresion-3d#validar" }] }
    ], sources: [{ label: "KeyShot · Studio", href: "https://www.keyshot.com/keyshot-studio/" }, { label: "KeyShot · Formatos compatibles", href: "https://manuals.keyshot.com/kss2026/en-us/manual/supported-file-formats.html" }, { label: "KeyShot · Licencias educativas", href: "https://www.keyshot.com/education/" }, { label: "Blender · Renderizado", href: "https://www.blender.org/features/rendering/" }, { label: "Blender · Licencia", href: "https://www.blender.org/about/license/" }]
  }
];
