export const productIdeas = [
  { id: "organizadores", title: "Organizadores a medida", media: "drawer-organizers", buyer: "Personas con un cajón o mesa difíciles de organizar", value: "Módulos ajustados al hueco y a los objetos reales.", check: "Mide el interior, deja margen para extraer los módulos y prueba el acabado de los bordes.", cost: "Tamaño de la base, paredes, horas de impresión y embalaje.", detail: "Empieza por un cajón concreto. Un conjunto de tres módulos permite mostrar la personalización sin ofrecer una colección enorme. Antes de hacer variantes, registra medidas y pregunta qué objetos deben caber.", portfolio: undefined },
  { id: "rotulos", title: "Placas y rótulos de sobremesa", media: "desk-sign", buyer: "Recepciones, puestos de trabajo y pequeños eventos", value: "Nombre, tamaño y placa intercambiable con un diseño propio.", check: "Comprueba legibilidad, estabilidad y montaje. Confirma el texto con el cliente antes de fabricar.", cost: "Preparación de cada variante, cambios de color y tiempo manual.", detail: "Define cuántos caracteres y revisiones incluye el encargo. Una base común con placa reemplazable puede facilitar nuevas variantes. La imagen es un concepto con placa en blanco; prepara una muestra real antes de anunciar el producto.", portfolio: undefined },
  { id: "taller", title: "Organización del taller", media: "tool-holders", buyer: "Usuarios de una mesa de trabajo o panel de herramientas", value: "Soportes adaptados a una herramienta o sistema de panel.", check: "Mide el panel y los útiles; valida fijación, inserción y carga prevista en la orientación de uso.", cost: "Diseño de la fijación, paredes, material y tiempo de comprobación.", detail: "Una familia pequeña para herramientas concretas suele ser más fácil de explicar que un gancho genérico. Publica dimensiones y compatibilidad comprobadas; no anuncies una carga admisible que no hayas validado.", portfolio: undefined },
  { id: "plantas", title: "Marcadores para plantas", media: "plant-labels", buyer: "Aficionados a pequeñas plantas y semilleros", value: "Identificación y tamaños adaptados al recipiente.", check: "Comprueba lectura, inserción y material según sol, humedad y duración del uso.", cost: "Lote, personalización y preparación del envío.", detail: "Puedes empezar con una serie corta de etiquetas. Separa las destinadas a interior de las expuestas al exterior y no prometas duración sin observar el material en esas condiciones.", portfolio: undefined },
  { id: "expositores", title: "Expositores para objetos pequeños", media: undefined, portfolio: 0, buyer: "Coleccionistas y pequeños comercios", value: "Apoyos y separación adaptados a la colección.", check: "Comprueba estabilidad con objetos reales y que los apoyos no dañen las superficies.", cost: "Volumen, número de apoyos, acabado y protección durante el envío.", detail: "El soporte de relojes del archivo propio sirve para observar la organización de apoyos. La foto no acredita ventas. Para ofrecer una variante, define qué medidas necesitas recibir y qué tipos de objeto puedes alojar." },
  { id: "decoracion", title: "Decoración con patrones propios", media: undefined, portfolio: 3, buyer: "Personas que buscan una pieza visual personalizada", value: "Patrón, proporción y color con una identidad propia.", check: "Revisa base, estabilidad y acabado. Para flores con agua, usa un recipiente interior salvo estanqueidad comprobada.", cost: "Altura, duración, fallos en capas altas y tamaño del paquete.", detail: "La textura helicoidal del archivo permite ver cómo un patrón puede aprovechar las capas. Una presentación con escala y varias vistas ayuda más que un render aislado. Comprueba que el diseño y sus recursos permitan la venta." },
  { id: "prototipos", title: "Cajas y prototipos de volumen", media: undefined, portfolio: 1, buyer: "Personas que necesitan comprobar dimensiones o montaje", value: "Una muestra física que permita decidir antes de fabricar la versión final.", check: "Acordad el objetivo de la muestra: forma, encaje o presentación, y qué queda fuera.", cost: "Modelado, cambios, horas de máquina y revisión dimensional.", detail: "Presupuesta por separado diseño y fabricación. No presentes una caja de prueba como una carcasa certificada para cualquier uso. Una muestra bien definida permite al cliente valorar el volumen y pedir una revisión concreta." },
  { id: "adaptadores", title: "Adaptadores para usos no críticos", media: undefined, portfolio: 4, buyer: "Usuarios con dos piezas que necesitan encajar", value: "Resolver una geometría o medida poco habitual.", check: "Mide ambas partes e imprime una probeta de ajuste antes de fabricar el adaptador completo.", cost: "Toma de medidas, iteraciones y material adecuado al entorno.", detail: "Acota el servicio a usos y condiciones que puedas comprobar. No incluyas aplicaciones de seguridad por defecto. La diferencia frente a una pieza genérica puede estar en el ajuste, pero ese ajuste debe probarse con medidas reales." }
];
