import "@/app/topic-guides.css";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { VisualFigure } from "@/components/VisualFigure";
import { productIdeas } from "@/lib/product-ideas";
import { getEditorialVisual } from "@/lib/editorial-media";
import { getPortfolioVisual } from "@/lib/visuals";
import { portfolioItems } from "@/lib/portfolio";
import { createPageMetadata, jsonLd } from "@/lib/seo";
import { absoluteUrl, siteConfig } from "@/lib/site";

export const metadata = createPageMetadata({ title: "Qué vender con impresión 3D: 8 ideas y cómo validar el margen", description: "Organizadores, rótulos, expositores y piezas a medida: ocho ideas para validar, con fotos, compradores posibles, comprobaciones y un ejemplo de costes.", path: "/que-vender-impresion-3d" });

export default function SellingGuidePage() {
  return <div className="cad-topic-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={jsonLd({ "@context": "https://schema.org", "@type": "Article", headline: "Qué vender con impresión 3D: 8 ideas y cómo validar el margen", description: metadata.description, mainEntityOfPage: absoluteUrl("/que-vender-impresion-3d"), author: { "@type": "Person", name: siteConfig.authorName, url: absoluteUrl("/sobre-mi") }, inLanguage: "es-ES", datePublished: "2026-09-09", dateModified: "2026-09-09" })} />
    <Breadcrumbs items={[{ label: "Guías", href: "/guias" }, { label: "Ideas para vender" }]} />
    <header className="cad-topic-header"><p className="cad-eyebrow">DEL DISEÑO AL PRIMER PEDIDO</p><h1>Qué vender con impresión 3D: empieza por una necesidad.</h1><p>Ocho familias de productos para explorar. Cada una incluye a quién podría servir, qué personalizar y qué comprobar antes de invertir en un lote.</p><div className="cad-topic-byline">Por <Link href="/sobre-mi">{siteConfig.authorName}</Link> · <time dateTime="2026-09-09">9 de septiembre de 2026</time></div></header>
    <nav className="cad-selling-index" aria-label="Secciones de la guía de venta"><a href="#ideas">Ocho ideas</a><a href="#validar">Validar la demanda</a><a href="#rentabilidad">Ejemplo de margen</a><a href="#licencias">Modelos y licencias</a><a href="#primer-pedido">Primer pedido</a></nav>
    <p className="cad-selling-note">Son propuestas para validar, no productos con ventas demostradas. Las imágenes combinan fotografías del archivo propio y cuatro conceptos ilustrados con IA, identificados en sus créditos.</p>
    <section id="ideas" className="cad-selling-ideas"><h2>Ocho puntos de partida</h2><div className="cad-product-detail-grid">{productIdeas.map(idea => {
      const piece = idea.portfolio !== undefined ? portfolioItems[idea.portfolio] : undefined;
      const visual = idea.media ? getEditorialVisual(idea.media) : getPortfolioVisual(piece!.image,piece!.alt);
      return <article id={idea.id} key={idea.id}><VisualFigure visual={visual} className={`cad-mag-photo${piece ? " cad-mag-photo-contain" : ""}`} sizes="(max-width: 760px) 90vw, 42vw" /><h3>{idea.title}</h3><p>{idea.detail}</p><dl><div><dt>Comprador posible</dt><dd>{idea.buyer}</dd></div><div><dt>Qué puedes aportar</dt><dd>{idea.value}</dd></div><div><dt>Qué validar</dt><dd>{idea.check}</dd></div><div><dt>Qué mueve el coste</dt><dd>{idea.cost}</dd></div></dl><Link className="cad-mag-link" href="/calculadora-precio-impresion-3d">Calcular una estimación</Link></article>;
    })}</div></section>
    <div className="cad-selling-reading cad-topic-body">
      <section id="validar"><h2>Cómo comprobar si alguien lo quiere comprar</h2><p>Elige un problema y un comprador concreto. Una pieza pequeña bien ajustada puede aportar más valor que un catálogo lleno de objetos sin destinatario. Antes de fabricar muchas unidades, prepara una muestra original y recoge respuestas a una propuesta con alcance y precio claros.</p><ol><li>Define medidas, material, acabado y qué incluye la personalización.</li><li>Imprime una muestra y registra gramos, tiempo y trabajo manual.</li><li>Haz fotos de la pieza real con escala y detalles de su función.</li><li>Presenta una oferta concreta y registra consultas y pedidos, sin confundir interés con ventas.</li><li>Revisa qué has gastado en cambios, fallos, embalaje y entrega.</li></ol><p>Si cambia la pieza, el precio o el canal a la vez, resulta difícil saber qué ha funcionado. Cambia una variable y conserva un registro sencillo.</p><a href="/downloads/registro-idea-producto.csv" download className="cad-mag-link">Descargar ficha de validación en CSV</a></section>
      <section id="rentabilidad"><h2>Vender por 15 € no significa ganar 15 €</h2><p>Ejemplo didáctico de una pieza FDM de 60 g y dos horas. Todos los importes son supuestos, sin impuestos ni envío; no son precios de mercado ni una previsión de ingresos. La comisión se fija en un 10 % solo para mostrar su efecto.</p><div className="cad-topic-table" tabIndex={0} role="region" aria-label="Ejemplo hipotético de costes"><table><thead><tr><th scope="col">Concepto</th><th scope="col">Supuesto</th><th scope="col">Coste</th></tr></thead><tbody>{[["Material", "60 g a 22 €/kg", "1,32 €"],["Máquina", "2 h a 0,45 €/h", "0,90 €"],["Electricidad", "2 h × 0,12 kW × 0,25 €/kWh", "0,06 €"],["Trabajo manual", "12 min a 15 €/h", "3,00 €"],["Embalaje", "Por unidad", "0,60 €"],["Reserva por reimpresiones", "10 % de material, máquina y energía, redondeado", "0,23 €"],["Comisión hipotética", "10 % de 15 €", "1,50 €"]].map(row => <tr key={row[0]}><th scope="row">{row[0]}</th><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody><tfoot><tr><th scope="row" colSpan={2}>Total de costes incluidos</th><td>7,61 €</td></tr></tfoot></table></div><p><strong>Quedarían 7,39 € por unidad</strong> para cubrir otros costes y el resultado del negocio. No es beneficio neto: faltan, por ejemplo, los gastos fijos que no hayas incluido, la captación, devoluciones e impuestos que correspondan.</p><p>Con estos mismos supuestos, cubrir 45 € adicionales de gastos fijos exigiría vender al menos siete unidades. Esa cuenta no demuestra que exista demanda. Si el mercado no acepta un precio que cubra el trabajo completo, modifica el producto, el proceso o la propuesta antes de aumentar el lote.</p><Link href="/calculadora-precio-impresion-3d" className="cad-mag-link">Calcular con tus propios datos</Link></section>
      <section id="licencias"><h2>Qué modelos puedes utilizar para vender</h2><p>La opción más clara es diseñar tu propio producto y conservar los archivos. Si utilizas un modelo ajeno, comprueba que su licencia permita vender impresiones físicas y qué condiciones exige. Que una descarga sea gratuita no concede por sí solo uso comercial; las licencias con cláusula NC lo restringen.</p><p>El canal de venta añade sus propias normas. Etsy exige actualmente que los artículos hechos con herramientas informáticas, incluidas impresoras 3D, se basen en un diseño original del vendedor. Una licencia comercial para imprimir un STL ajeno no garantiza cumplir esa regla. Revisa también la licencia del programa con el que modelas.</p><ul><li><a href="https://www.etsy.com/legal/creativity/" target="_blank" rel="noreferrer">Etsy · Normas de creatividad</a></li><li><a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noreferrer">Creative Commons · Qué significa No Comercial</a></li><li><a href="https://blog.prusa3d.com/printables-store_87810/" target="_blank" rel="noreferrer">Printables · Diferencia entre licencias de modelos</a></li></ul><Link href="/programas-modelado-3d" className="cad-mag-link">Elegir software y revisar su licencia</Link></section>
      <section id="primer-pedido"><h2>Deja claro qué recibirá el comprador</h2><p>Confirma dimensiones, color, material, texto y plazo. Indica qué revisiones incluye el diseño y qué puede variar en el acabado. Utiliza fotografías de la muestra terminada; si muestras un render, identifícalo y acompáñalo de información suficiente sobre el objeto real.</p><p>Una primera entrega sirve para comprobar el proceso completo: preparación, impresión, revisión, embalaje y atención al comprador. Si el pedido requiere una función que no puedes verificar, acota la oferta antes de aceptarlo.</p><div className="cad-topic-links"><Link href="/checklist-impresion-3d">Comprobar una impresión</Link><Link href="/keyshot-vs-blender-renderizado">Preparar renders de presentación</Link><Link href="/laboratorio-tolerancias-fdm">Validar encajes</Link></div></section>
    </div>
  </div>;
}
